In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
df=pd.read_csv("/content/titanic (1).csv")
df.shape

(891, 12)

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# replacing cabin feature null values with forward values
import warnings
warnings.filterwarnings('ignore')
df['Cabin']=df['Cabin'].fillna(method='ffill')

In [ ]:
#calculating the null values in cabin feature
df['Cabin'].isnull().sum()

1

In [ ]:
#replacing that one null value backward value in cabin feature
df['Cabin']=df['Cabin'].fillna(method='bfill')
df['Cabin'].isnull().sum()

0

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin            0
Embarked         2
dtype: int64

In [ ]:
# calculating mean value for age feature
mean=df['Age'].mean()
mean

29.69911764705882

In [ ]:
# replacing nan values with mean of Age
import numpy as np
df['Age']=df['Age'].replace(np.NaN,mean)

In [ ]:
df['Age'].isnull().sum()

0

In [ ]:
# replacing embarked  feature null values with forward values
df['Embarked']=df['Embarked'].fillna(method='ffill')

In [ ]:
df['Embarked'].isnull().sum()

0

In [ ]:
# there are no null values in the dataset
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,C85,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,C85,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,C123,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,C50,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,C148,Q

In [ ]:
# changing the age data type from float to int
df['Age']=df['Age'].astype('int')

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age              int64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,C85,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,C85,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,C123,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,C50,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29,1,2,W./C. 6607,23.4500,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,C148,Q

In [ ]:
x=({'male':0,'female':1})
data['Sex']=data['Sex'].map(x)

In [ ]:
data

     Survived  Pclass  Sex  Age     Fare
0           0       3    0   22   7.2500
1           1       1    1   38  71.2833
2           1       3    1   26   7.9250
3           1       1    1   35  53.1000
4           0       3    0   35   8.0500
..        ...     ...  ...  ...      ...
886         0       2    0   27  13.0000
887         1       1    1   19  30.0000
888         0       3    1   29  23.4500
889         1       1    0   26  30.0000
890         0       3    0   32   7.7500

[891 rows x 5 columns]

In [ ]:
# dropping the features that do not impact on survuval rate
data=df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis=1)

In [ ]:
target=data['Survived']
inputs=data.drop(['Survived'],axis=1)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2)
print(len(X_train), len(X_test), len(inputs))

712 179 891

In [ ]:
from sklearn.naive_bayes import GaussianNB
# fitting the model
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [ ]:
model.score(X_test, y_test)

0.6871508379888268

In [ ]:
pred = np.array(model.predict(X_test))
pred_probability = np.array(model.predict_proba(X_test)) # calculating the probabilities

print(pred[:10])
print(pred_probability[:10])

[0 1 1 0 0 0 0 1 1 1]
[[9.47498970e-01 5.25010304e-02]
 [7.04609512e-08 9.99999930e-01]
 [1.50262982e-01 8.49737018e-01]
 [7.75578925e-01 2.24421075e-01]
 [9.69875323e-01 3.01246775e-02]
 [9.38035361e-01 6.19646394e-02]
 [9.69192178e-01 3.08078218e-02]
 [2.87294900e-01 7.12705100e-01]
 [3.06637987e-01 6.93362013e-01]
 [1.21265843e-02 9.87873416e-01]]